TRAIN_PATH = "data/coco/train2014"
VALID_PATH = "data/coco/val2014"
TEST_PATH = "data/coco/test2014"

IMG_SIZE = (256, 128)
GLIMPSE_SIZE = 16
GLIMPSES_W, GLIMPSES_H = IMG_SIZE[0] // GLIMPSE_SIZE, IMG_SIZE[1] // GLIMPSE_SIZE
