name: wtln
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - alsa-lib=1.2.3.2
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=2.16
  - bleach=5.0.1
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - commonmark=0.9.1
  - contourpy=1.0.2
  - cryptography=37.0.2
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.4.8
  - ffmpeg=4.3
  - filelock=3.8.0
  - flit-core=3.8.0
  - fontconfig=2.13.1
  - fonttools=4.38.0
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.11.0
  - future=0.18.2
  - gds-tools=1.4.0.31
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.29
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.14.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - huggingface_hub=0.11.1
  - icu=68.2
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_metadata=5.1.0
  - importlib_resources=5.10.1
  - intel-openmp=2022.1.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.3
  - jbig=2.1
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.0
  - jupyter_server=1.23.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.4
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libblas=3.8.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.8.0
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.4
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm11=11.1.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2020.2
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.6
  - nbconvert-core=7.2.6
  - nbconvert-pandoc=7.2.6
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.3.0.22
  - nspr=4.32
  - nss=3.69
  - numpy=1.22.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.0
  - prometheus_client=0.15.0
  - promise=2.3
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protobuf=3.20.1
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.13.0
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=23.0.0
  - qt=5.12.9
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rich=12.6.0
  - rsa=4.9
  - send2trash=1.8.0
  - sentry-sdk=1.11.1
  - setproctitle=1.2.3
  - setuptools=65.5.0
  - shortuuid=1.0.11
  - six=1.16.0
  - smmap=3.0.5
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - timm=0.6.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchmetrics=0.10.3
  - torchvision=0.14.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - wandb=0.13.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - werkzeug=2.2.2
  - wheel=0.37.1
  - widgetsnbextension=4.0.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.0
