name: wtln
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=5.0.1
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - commonmark=0.9.1
  - contourpy=1.0.6
  - cryptography=39.0.0
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.76
  - cuda-documentation=12.0.76
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.90
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.9.0
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - future=0.18.2
  - gds-tools=1.5.0.59
  - gettext=0.21.1
  - gitdb=4.0.10
  - gitpython=3.1.30
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.51.1
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - huggingface_hub=0.11.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - intel-openmp=2022.1.0
  - ipykernel=6.20.1
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jack=1.9.21
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.3
  - jupyter_events=0.6.2
  - jupyter_server=2.0.6
  - jupyter_server_terminals=0.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.5
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcups=2.3.3
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libgrpc=1.51.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm15=15.0.6
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsndfile=1.1.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lightning-utilities=0.5.0
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - mpg123=1.31.1
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.7
  - nbconvert-core=7.2.7
  - nbconvert-pandoc=7.2.7
  - nbformat=5.7.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.82
  - numpy=1.24.1
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=22.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - ply=3.11
  - pooch=1.6.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protobuf=4.21.12
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-lightning=1.8.1
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.0.1
  - rsa=4.9
  - scipy=1.10.0
  - send2trash=1.8.0
  - sentry-sdk=1.12.1
  - setproctitle=1.3.2
  - setuptools=65.6.3
  - sip=6.7.5
  - six=1.16.0
  - smmap=3.0.5
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - timm=0.6.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - torchmetrics=0.11.0
  - torchvision=0.14.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wandb=0.13.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - werkzeug=2.2.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
