name: wtln
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=2.16
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - cryptography=37.0.2
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - docker-pycreds=0.4.0
  - ffmpeg=4.3
  - filelock=3.8.0
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.11.0
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.29
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.14.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - huggingface_hub=0.11.1
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_metadata=5.1.0
  - intel-openmp=2022.1.0
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.7
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.17
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2020.2
  - multidict=6.0.2
  - ncurses=6.3
  - nettle=3.6
  - nsight-compute=2022.3.0.22
  - numpy=1.22.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pathtools=0.1.2
  - pillow=9.2.0
  - pip=22.2.2
  - promise=2.3
  - protobuf=3.20.1
  - psutil=5.9.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.8
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - sentry-sdk=1.11.1
  - setproctitle=1.2.3
  - setuptools=65.5.0
  - shortuuid=1.0.11
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.40.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - timm=0.6.12
  - tk=8.6.12
  - torchmetrics=0.10.3
  - torchvision=0.14.0
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - urllib3=1.26.13
  - wandb=0.13.5
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.0
